### ISSUE TITLE
feature request: tiled area

### ISSUE THREAD

**Issue by sevenoffline** [fgebhart/mapa#45]
How about offering the possibility to cut the selected (square) area into (square) tiles - 3x3 & 4x4 should be sufficient. 
With this feature it would be possible to print a larger area in pieces that can be glued together.

**Comment by fgebhart** [comment]
Sounds like a good idea and I will investigate what it would need for this to be implemented.

Maybe this does not even need to be restricted to square shapes and could also be applied to rectangles in general. I'm thinking of an approach which would work for both.

**Comment by sevenoffline** [comment]
Maybe my imagination was too arty by limiting that feature to squares :D You're right, a general approach is much more functional.

**Comment by fgebhart** [comment]
Just rolled out the tiling feature! Would love to hear what you think 🙂 

Give it a try, as usually here: https://share.streamlit.io/fgebhart/mapa-streamlit/main/app.py

Also note, that STL files are now zipped as default. As mentioned already elsewhere, this reduces data volume transferred via the network by a factor of three to four. However, it also requires more time to compress the STL file(s), but I also included the zipping into the progress bar to make things transparent.

All STL files within one zip file are of equal data quality / resolution. I will try to see if it would make sense to also make the resolution limit configurable going forward (as requested in #60).

**Comment by sevenoffline** [comment]
Another thing: the Z-height-scale is different - the 1x1 is taller than the 3x3. Look: https://imgur.com/a/uifba3b
