### ISSUE TITLE
Bug: bottom surface not connected

### ISSUE THREAD

**Issue by sevenoffline** [fgebhart/mapa#50]
The generated model's bottom surface has two flaws:

1. It is not connected to the side walls so those edges down there are all open. This was reported in the slicer and I verified it in an 3D-tool.
2. It is not triangulated properly (only once into two triangles): all those edges coming down the side walls from the top relief end and are not continued further to e.g. a center vertex. This results in two massive n-gons the bottom surface is made of.

Maybe these two issues are related?

**Comment by sevenoffline** [comment]
To further clarify what I'm trying to express, here a picture to illustrate:
https://imgur.com/a/4ei2K9s

**Comment by fgebhart** [comment]
Thanks for adding the screenshots. I still need to need to investigate this. Is there any free mesh analyzing tool you would recommend (for unix systems?).

**Comment by sevenoffline** [comment]
I'm only familiar with 3D on Win, unfortunately. But Blender should be more than capable to show & filter edgeflow and open edges. 

Sidenote: maybe not the most economical approach but how about duplicating the top relief, moving it downwards by the z-offset value, flatten it and create the side walls by connecting the (same numbered) edge-vertices?

**Comment by fgebhart** [comment]
> how about duplicating the top relief, moving it downwards by the z-offset value, flatten it and create the side walls by connecting the (same numbered) edge-vertices?

Yes, I do basically have the top relief already at hand before even "extruding the 3d shape". Thus I could simply copy that and put it to z=0. However, that will likely blow up the STL file in size, as it almost duplicates the number of triangles.

Originally I simply went with only 2 triangles for the button surface and I still wonder why this is okay for two sides of the model but not for the other two. :thinking:

**Comment by sevenoffline** [comment]
Well, right now all four sides are connected to the top relief! But no side is connected to the bottom - maybe because it's only made of only two triangles?! Is it possible to create one center vertex on the bottom side and connect all side-vertices with that one? That would result in the most efficient triangulation possible for the bottom side.

**Comment by fgebhart** [comment]
Ah, from your image reading "GOOD" I assumed two sides are in fact connected to the bottom.

Unfortunately the [STL file format](http://www.fabbers.com/tech/STL_Format) does not have such thing as "connect to". It consists of triangles, which consist of coordinates only. With that I assume having the same number of triangles in the bottom as in the top relief is the way forward for solving this issue.

**Comment by fgebhart** [comment]
Ok, I am able to verify the bottom not being closed with any of the sides using blender. Orange highlighted are open connections:

![Screenshot from 2022-04-01 11-03-26](https://user-images.githubusercontent.com/16943048/161232177-cddf36bf-7f07-45b7-9dbf-1288e111fbef.png)

**Comment by sevenoffline** [comment]
See? So if all polygons have to be triangles, those edges coming down the sides must be connected to some vertex on the bottom side (like the typical cylinder-primitive).

**Comment by fgebhart** [comment]
I gave duplicating the top mesh a try. Unsurprisingly it does double the size of the STL file. Even though the implementation is rather straight forward and easy to maintain I don't like the solution. A laptop with 8GB ram quickly comes into out of memory issues when post processing files of a few hundreds of MB in blender.

Which is why I'm looking for a more efficient way to construct the bottom side with less triangles. Did a quick sketch and think I found something. It also seems to work with rectangles :slightly_smiling_face: 

![2022-04-01 21 39 54](https://user-images.githubusercontent.com/16943048/161332288-978cbc7b-4bad-4a38-9a93-413683288276.jpg)

However, still need to find a performant implementation.

**Comment by fgebhart** [comment]
Just putting this here for future reference:

Plot of the bottom triangles:
<img width="577" alt="Screenshot 2022-04-05 at 21 37 43" src="https://user-images.githubusercontent.com/16943048/161835935-800febd5-c275-43e1-88b3-e6e02dc376f4.png">

Created using branch: 
https://github.com/fgebhart/mapa/tree/plot_bottom_triangulation

**Comment by fgebhart** [comment]
The issue should be fixed by https://github.com/fgebhart/mapa/pull/53 and https://github.com/fgebhart/mapa/pull/55.

However, a new mapa version is not yet released and not integration into the streamlit app. Should be done soon, though.

**Comment by fgebhart** [comment]
Have released [mapa v0.8.0](https://github.com/fgebhart/mapa/releases/tag/v0.8.0) and rolled the changes out in [mapa-streamlit v0.6.0](https://github.com/fgebhart/mapa-streamlit/releases/tag/v0.6.0).

Let me know if there are still issues with unclosed connections between triangles.

**Comment by sevenoffline** [comment]
Perfect! Flawless, great job!
