### ISSUE TITLE
feature request: display version-number in app

### ISSUE THREAD

**Issue by sevenoffline** [fgebhart/mapa#51]
Pls display the app's version number in e.g. the "About"-window. When testing it I refresh the page but I can't be sure if it's properly reloaded or if I have to flush my browser cache. Having a version number would be great to verify.

**Comment by fgebhart** [comment]
I do already display the[ version of `mapa-streamlit`](https://github.com/fgebhart/mapa-streamlit/blob/main/pyproject.toml#L3) in the "about" section. Though I have to admit I did not update it for each little change.

But I guess you would be more interested in including the [version of `mapa`](https://github.com/fgebhart/mapa/blob/main/pyproject.toml#L3) within the about section, right?

**Comment by fgebhart** [comment]
I've just [added the version of `mapa` also to the about section](https://github.com/fgebhart/mapa-streamlit/pull/25). Furthermore I started adding [tags and releases to the mapa-streamlit repo](https://github.com/fgebhart/mapa-streamlit/releases). Thus it should be more transparent, which version of mapa-streamlit incorporates which changes.
